site: M4r10
title: M4r10's Blog
greetings: M4r10's Blog
description: >-
  just a minimalist, personal blog
lang: en-US
timezone:  India/kolkata
repo: https://github.com/th3m4r10/th3m4r10.github.io/ # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: m4r10 # replace with your disqus shortname

author:
  name: m4r10
  bio: just a minimalist, personal blog
  userpicture: 
  username: # general username
  github: # github username
  twitter: # twitter username
  email: muraligari2365@gmail.com # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: https://th3m4r10.github.io # Domain Name of host. [username].github.io for github pages
baseurl: 
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


